import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'index',
    {
      type: 'category',
      label: 'Start Here',
      collapsed: false,
      items: [
        'start-here/overview',
        'start-here/quickstart',
        'start-here/repo-tour',
        'start-here/dev-environment',
        'start-here/glossary',
      ],
    },
    {
      type: 'category',
      label: 'Architecture',
      collapsed: false,
      items: [
        'architecture/pipeline',
        'architecture/events',
        'architecture/nats',
        'architecture/storage',
      ],
    },
    {
      type: 'category',
      label: 'Services',
      collapsed: false,
      items: [
        'services/ingestor',
        'services/decoder',
        'services/sinks',
        'services/api',
        'services/bridge',
        'services/backfill',
      ],
    },
    {
      type: 'category',
      label: 'Ops',
      collapsed: true,
      items: [
        'ops/local-dev',
        'ops/nats-jetstream',
        'ops/clickhouse',
        'ops/deploy',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      collapsed: true,
      items: [
        'reference/env',
        'reference/cli',
        'reference/legacy-archive',
        {
          type: 'category',
          label: 'Code Reference',
          collapsed: true,
          items: [{type: 'autogenerated', dirName: 'reference/code'}],
        },
      ],
    },
  ],
};

export default sidebars;
